# Generated by Django 4.1.5 on 2023-07-12 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_additionalfees_month_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfees',
            name='month_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 14, 54, 59, 809334)),
        ),
    ]
