from .models import *
def porter_out(table):
    b_rec = BarangayRecord()
    for i in table:
        b_rec.barangay_val = i[0]
        b_rec.year = i[2]
        b_rec.total_due_jan = i[6]
        b_rec.total_paid_jan = i[7]
        b_rec.total_usage_jan = i[8]
        b_rec.total_due_feb = i[9]
        b_rec.total_paid_feb = i[10]
        b_rec.total_usage_feb = i[11]
        b_rec.total_due_mar = i[12]
        b_rec.total_paid_mar = i[13]
        b_rec.total_usage_mar = i[14]
        b_rec.total_due_apr = i[15]
        b_rec.total_paid_apr = i[16]
        b_rec.total_usage_apr = i[17]
        b_rec.total_due_may = i[18]
        b_rec.total_paid_may = i[19]
        b_rec.total_usage_may = i[20]
        b_rec.total_due_jun = i[21]
        b_rec.total_paid_jun = i[22]
        b_rec.total_usage_jun = i[23]
        b_rec.total_due_jul = i[24]
        b_rec.total_paid_jul = i[25]
        b_rec.total_usage_jul = i[26]
        b_rec.total_due_aug = i[27]
        b_rec.total_paid_aug = i[28]
        b_rec.total_usage_aug = i[29]
        b_rec.total_due_sept = i[30]
        b_rec.total_paid_sept = i[31]
        b_rec.total_usage_sept = i[32]
        b_rec.total_due_oct = i[33]
        b_rec.total_paid_oct = i[34]
        b_rec.total_usage_oct = i[35]
        b_rec.total_due_nov = i[36]
        b_rec.total_paid_nov = i[37]
        b_rec.total_usage_nov = i[38]
        b_rec.total_due_dec = i[39]
        b_rec.total_paid_dec = i[40]
        b_rec.total_usage_dec = i[41]
        b_rec.save()