class ReqParams():
    #session attributes
    template = "template"
    postedby = "postedby"
    reading_postedby = "reading_postedby"
    username = "username"
    LOGIN_SESSION = "LogInSession"
    TELLER_LOGIN_VAL = "2"
    ADMIN_LOGIN_VAL = "1"
    SUPERVISOR_LOGIN_VAL = "3"
    INPUTREADER_LOGIN_VAL = "5"
    MANAGER_LOGIN_VAL = "4"
    name = "name"
    verification_code = "verification_code"
    remember_me = "remember_me"
    ACCOUNTID_VAL = "accountinfoidval"
    vcode_expiry = "vcode_expiry"