from calendar import c
from datetime import date
from pyexpat import model
from tkinter import CASCADE
from urllib import request
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class SystemUsers(AbstractUser):
    password = models.BinaryField(max_length=450)
    username = models.CharField(primary_key=True, max_length=20)
    is_admin = models.BooleanField(default=False)
    is_teller = models.BooleanField(default=False)
    is_supervisor = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    is_reader = models.BooleanField(default=False)
    mid_name = models.CharField(max_length=20, blank=True)
    mobilenum = models.CharField(max_length=20, blank=True)
    profilepic = models.ImageField(blank=True, null=True)
    mobilenum = models.CharField(max_length=20, blank=True)
    authorizedapprover = models.CharField(max_length=20, default='0')
class Rates(models.Model):
    rateid = models.CharField(primary_key=True, max_length=20)
    minReading = models.IntegerField()
    minReadingCharge = models.IntegerField()
    rateAfterMin = models.IntegerField()
    ratePenalty = models.IntegerField()
    ratePenaltyFreq = models.IntegerField()
class Barangays(models.Model):
    barangay = models.CharField(max_length=20, blank=True)
class BarangayRecord(models.Model):
    barangay_val = models.CharField(primary_key=True, max_length=10,)
    year = models.IntegerField()
    total_due_jan = models.IntegerField()
    total_paid_jan = models.IntegerField()
    total_usage_jan = models.IntegerField()
    total_due_feb = models.IntegerField()
    total_paid_feb = models.IntegerField()
    total_usage_feb = models.IntegerField()
    total_due_mar = models.IntegerField()
    total_paid_mar = models.IntegerField()
    total_usage_mar = models.IntegerField()
    total_due_apr = models.IntegerField()
    total_paid_apr = models.IntegerField()
    total_usage_apr = models.IntegerField()
    total_due_may = models.IntegerField()
    total_paid_may = models.IntegerField()
    total_usage_may = models.IntegerField()
    total_due_jun = models.IntegerField()
    total_paid_jun = models.IntegerField()
    total_usage_jun = models.IntegerField()
    total_due_jul = models.IntegerField()
    total_paid_jul = models.IntegerField()
    total_usage_jul = models.IntegerField()
    total_due_aug = models.IntegerField()
    total_paid_aug = models.IntegerField()
    total_usage_aug = models.IntegerField()
    total_due_sept = models.IntegerField()
    total_paid_sept = models.IntegerField()
    total_usage_sept = models.IntegerField()
    total_due_oct = models.IntegerField()
    total_paid_oct = models.IntegerField()
    total_usage_oct = models.IntegerField()
    total_due_nov = models.IntegerField()
    total_paid_nov = models.IntegerField()
    total_usage_nov = models.IntegerField()
    total_due_dec = models.IntegerField()
    total_paid_dec = models.IntegerField()
    total_usage_dec = models.IntegerField()
class ConsumerInfo(models.Model):
    consumer_id = models.CharField(primary_key=True, max_length=20)
    meternumber = models.CharField(max_length=20, blank=True, null=True)
    firstname = models.CharField(max_length=50, blank=True)
    lastname = models.CharField(max_length=50, blank=True)
    middlename = models.CharField(max_length=50, blank=True)
    barangaycode = models.ForeignKey(Barangays, on_delete=models.CASCADE)
    initialmeterreading = models.IntegerField()
    rateid = models.ForeignKey(Rates,on_delete=models.CASCADE)
    status = models.IntegerField()
    penaltyflag = models.BooleanField()
    stopmeterflag = models.BooleanField()
    deleteflag = models.BooleanField()
class Penalties(models.Model):
    penalty = models.IntegerField()
class Discounts(models.Model):
    discount = models.IntegerField()
class Transactions(models.Model):
    TRANS_TYPE = (
        ('j','j'),
    )
    date = models.DateField()
    acctID = models.ForeignKey(ConsumerInfo, on_delete=models.CASCADE)
    transType = models.CharField(max_length=20, choices=TRANS_TYPE)
    meterReading = models.IntegerField()
    ratescode = models.ForeignKey(Rates, on_delete= models.CASCADE)
    penaltyCode = models.ForeignKey(Penalties, on_delete= models.CASCADE)
    discountcode = models.ForeignKey(Discounts, on_delete= models.CASCADE)
    payment = models.IntegerField()
    processedBy = models.ForeignKey(SystemUsers, on_delete=models.CASCADE)