from . import views
from django.urls import path


urlpatterns = [
    path('port',views.porter,name='port'),
    path('',views.lp,name='landing'),
    path('login/',views.signin,name='login'),
    path('user_creation', views.user_creation,name='user_creation'),
    path('signout', views.signout,name='signout'),
    path('bills_list', views.bills_list, name='bills_list'),
    path('bills_list/ledger/<id>/', views.ledger,name='ledger'),
    path('bills_list/ledger/conmon_summary/<id>/<int:year>', views.monthly_summary,name='monthly_summary'),
    path('bills_list/ledger/payment_history/<id>/<int:year>', views.payment_history,name='payment_history'),
    path('editpayment/<id>/', views.editpayment,name='editpayment'),
    path('payment/<id>/', views.payment, name='payment'),
    path('monthlypayment/', views.monthlypayment, name='monthlypayment'),
    path('meterreading', views.meterreading,name='meterreading'),
    path('meterreading/bulkreading', views.bulkreading,name='bulkreading'),
    path('meterreading/deletereading/<int:id>', views.deletereading,name='deletereading'),
    path('meterreading/<id>/<int:year>', views.inputreading,name='inputreading'),
    path('forgetpassword', views.forgetpassword,name='forgetpassword'),
    path('resetpassword/<uidb64>/<token>', views.resetpassword,name='resetpassword'),
    path('stopmeter/<id>', views.stopmeter,name='stopmeter'),
    path('enablemeter/<id>', views.enablemeter,name='enablemeter'),
    path('consumercreation', views.consumercreation,name='consumercreation'),
    path('consumer_list/', views.consumer_list, name='consumer_list'),
    path('consumer_list/consumercreation', views.consumercreation,name='consumercreation'),
    path('consumer_list/<id>/', views.consumerupdate, name='consumerupdate'),
    path('deleteconsumer', views.deleteconsumer,name='deleteconsumer'),
    path('disconnectconsumer/<id>', views.disconnectconsumer,name='disconnectconsumer'),
    path('reconnectconsumer/<id>', views.reconnectconsumer,name='reconnectconsumer'),
    path('sysuser/', views.sysuser,name='sysuser'),
    path('sysuser/user_creation', views.user_creation,name='user_creation'),
    path('sysuser/edit/<id>/', views.user_edit, name='user_edit'),
    path('deleteUser/<id>/', views.deleteUser, name='deleteUser'),
    path('about', views.about, name='about'),
    path('reports', views.reports, name='reports'),
    path('reports/barangayreport/<int:year>', views.barangayreport, name='barangayreport'),
    path('reports/view_barangay/<id>/', views.view_barangay, name='view_barangay'),
    path('reports/usage_report_data/<int:year>', views.usage_report_data, name='usage_report_data'),
    path('reports/revenue_report/<int:year>', views.revenue_report, name='revenue_report'),
    path('reports/consumption/<int:year>', views.consumption, name='consumption'),
    path('unsettled_bills',views.unsettled_bills, name='unsettled_bills'),
    path('unsettled_bills/<id>/<int:year>',views.view_unsettled_bills, name='view_unsettled_bills'),
    path('payment/<id>/', views.payment, name='payment'),
    path('settings/new_consumertype', views.new_consumertype, name='new_consumertype'),
    path('settings/new_consumertype/editcontype/<id>', views.editcontype, name='editcontype'),
    path('settings/discount',views.discount, name='discount'),
    path('settings/discount/editdiscount/<id>', views.editdiscount, name='editdiscount'),
    path('settings/deletediscount/<id>', views.deletediscount, name='deletediscount'),
    path('settings/penalty', views.penalty, name='penalty'),
    path('settings/penalty/editpenalty/<id>', views.editpenalty, name='editpenalty'),
    path('settings/exemptions/', views.exemption, name= 'exemptions'),
    path('settings/userprof', views.userprof, name='userprof'),
    path('settings', views.viewprof, name='settings'),
    path('stopmeters', views.stopmeters, name='stopmeters'),
]

