<<<<<<< HEAD
# Generated by Django 4.1.3 on 2023-02-11 03:44
=======
# Generated by Django 4.1.5 on 2023-02-07 01:47
>>>>>>> e468dea26d75b95be146daf09b9fb6e969dfb03a

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemUsers",
            fields=[
<<<<<<< HEAD
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=20)),
                ("last_name", models.CharField(blank=True, max_length=20)),
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_teller", models.BooleanField(default=False)),
                ("is_supervisor", models.BooleanField(default=False)),
                ("is_manager", models.BooleanField(default=False)),
                ("is_reader", models.BooleanField(default=False)),
                ("mid_name", models.CharField(blank=True, max_length=20)),
                ("mobilenum", models.CharField(blank=True, max_length=20)),
                ("authorizedapprover", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "profilepic",
                    models.ImageField(
                        blank=True, default="profile12.png", null=True, upload_to=""
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
=======
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_teller', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_reader', models.BooleanField(default=False)),
                ('mid_name', models.CharField(blank=True, max_length=20)),
                ('mobilenum', models.CharField(blank=True, max_length=20)),
                ('authorizedapprover', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('profilepic', models.ImageField(blank=True, default='profile12.png', null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
>>>>>>> e468dea26d75b95be146daf09b9fb6e969dfb03a
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Barangays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barangay", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ConsumerInfo",
            fields=[
<<<<<<< HEAD
                (
                    "consumer_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("meternumber", models.CharField(blank=True, max_length=20, null=True)),
                ("firstname", models.CharField(blank=True, max_length=50)),
                ("lastname", models.CharField(blank=True, max_length=50)),
                ("middlename", models.CharField(blank=True, max_length=50)),
                ("homeaddress", models.CharField(blank=True, max_length=50)),
                ("initialmeterreading", models.IntegerField()),
                ("status", models.IntegerField()),
                ("penaltycounter", models.IntegerField(null=True)),
                ("stopmeterflag", models.BooleanField()),
                ("deleteflag", models.BooleanField()),
                ("disconnectionflag", models.BooleanField()),
                ("mobilenum", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, max_length=6, null=True)),
                ("sitio", models.CharField(blank=True, max_length=100, null=True)),
                ("picture", models.ImageField(blank=True, null=True, upload_to="")),
                ("current_bal", models.FloatField(default=0)),
                ("current_reading", models.IntegerField(default=0)),
                ("cummulative", models.FloatField(default=0)),
                ("date_added", models.DateField(auto_now_add=True, null=True)),
                ("excess", models.IntegerField(default=0)),
=======
                ('consumer_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('meternumber', models.CharField(blank=True, max_length=20, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50)),
                ('homeaddress', models.CharField(blank=True, max_length=50)),
                ('initialmeterreading', models.IntegerField()),
                ('status', models.IntegerField()),
                ('penaltycounter', models.IntegerField(null=True)),
                ('stopmeterflag', models.BooleanField()),
                ('deleteflag', models.BooleanField()),
                ('disconnectionflag', models.BooleanField()),
                ('mobilenum', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=6, null=True)),
                ('sitio', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('current_bal', models.FloatField(default=0)),
                ('cummulative', models.FloatField(default=0)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginRec',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=10)),
                ('last_access', models.DateTimeField()),
                ('expiration', models.DateTimeField(default=datetime.datetime(2023, 2, 7, 9, 47, 40, 425823))),
>>>>>>> e468dea26d75b95be146daf09b9fb6e969dfb03a
            ],
        ),
        migrations.CreateModel(
            name="LoginRec",
            fields=[
<<<<<<< HEAD
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("token", models.CharField(max_length=10)),
                ("last_access", models.DateTimeField()),
                (
                    "expiration",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 11, 11, 44, 17, 729038)
                    ),
                ),
=======
                ('penaltycode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('penalty_after', models.IntegerField(default=0)),
                ('penalty_rate', models.FloatField(default=0)),
                ('penalty_info', models.TextField(blank=True, max_length=300, null=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('daysappliedafter', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
>>>>>>> e468dea26d75b95be146daf09b9fb6e969dfb03a
            ],
        ),
        migrations.CreateModel(
            name="Penalty",
            fields=[
                (
                    "penaltycode",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("penalty_after", models.IntegerField(default=0)),
                ("penalty_rate", models.FloatField(default=0)),
                (
                    "penalty_info",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("date_added", models.DateField(auto_now_add=True, null=True)),
                ("daysappliedafter", models.IntegerField(default=0)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name="revenuecode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_fee", models.FloatField(default=0)),
                ("mayors_permit", models.FloatField(default=0)),
                ("gravel_excavation", models.FloatField(default=0)),
                ("asphalted_road", models.FloatField(default=0)),
                ("cemented_road", models.FloatField(default=0)),
                ("additionalfee_pipe_of_20_lineal_feet", models.FloatField(default=0)),
                ("residentialservice_per_month", models.FloatField(default=0)),
                ("commercialservice_per_month", models.FloatField(default=0)),
                (
                    "residentialservice_excess_per_cubicmeter",
                    models.FloatField(default=0),
                ),
                (
                    "commercialservice_excess_per_cubicmeter",
                    models.FloatField(default=0),
                ),
                ("drilling_from_mainline", models.FloatField(default=0)),
                ("reinstallation_fee", models.FloatField(default=0)),
                ("tapping_fee", models.FloatField(default=0)),
                ("repair_fee", models.FloatField(default=0)),
                ("transfer_fee", models.FloatField(default=0)),
                ("three_month_penalty", models.FloatField(default=0)),
                ("send_disconnection_notice_after", models.IntegerField(default=0)),
                ("disconnection_after", models.IntegerField(default=0)),
                ("penalty_after", models.IntegerField(default=0)),
                ("fix_amount_penalty", models.FloatField(default=0)),
                ("percentage_penalty", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("transactionid", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "transType",
                    models.CharField(
                        choices=[
                            ("Billing", "Billing"),
                            ("Payment", "Payment"),
                            ("Penalty", "Penalty"),
                            ("Discount", "Discount"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meterReading", models.IntegerField(blank=True, null=True)),
                ("prevReading", models.IntegerField(blank=True, null=True)),
                ("usage", models.IntegerField(blank=True, null=True)),
                ("contypeid", models.CharField(blank=True, max_length=20, null=True)),
                ("discountcode", models.CharField(max_length=50, null=True)),
                ("bill", models.FloatField(null=True)),
                ("is_billpaid", models.BooleanField(default=False)),
                ("month", models.IntegerField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("receivedamt", models.FloatField(null=True)),
                ("payment", models.FloatField(null=True)),
                ("processedBy", models.CharField(max_length=50, null=True)),
                ("or_number", models.CharField(max_length=100)),
                (
                    "acctID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.consumerinfo",
                    ),
                ),
                (
                    "penaltyCode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="index.penalty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "discountcode",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("discount_rate", models.IntegerField()),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsumerType",
=======
            name='Transactions',
            fields=[
                ('transactionid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('transType', models.CharField(choices=[('Billing', 'Billing'), ('Payment', 'Payment'), ('Penalty', 'Penalty'), ('Discount', 'Discount')], max_length=20)),
                ('meterReading', models.IntegerField(blank=True, null=True)),
                ('prevReading', models.IntegerField(blank=True, null=True)),
                ('usage', models.IntegerField(blank=True, null=True)),
                ('contypeid', models.CharField(blank=True, max_length=20, null=True)),
                ('discountcode', models.CharField(max_length=50, null=True)),
                ('bill', models.FloatField(null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('payment', models.FloatField(null=True)),
                ('processedBy', models.CharField(max_length=50, null=True)),
                ('or_number', models.CharField(max_length=100)),
                ('acctID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.consumerinfo')),
                ('penaltyCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.penalty')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discountcode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('discount_rate', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerType',
>>>>>>> e468dea26d75b95be146daf09b9fb6e969dfb03a
            fields=[
                (
                    "contypeid",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("contype", models.CharField(max_length=20)),
                ("minReading", models.IntegerField()),
                ("minReadingCharge", models.IntegerField()),
                ("rateAfterMin", models.IntegerField()),
                ("date_added", models.DateField(auto_now_add=True)),
                ("date_mod", models.DateField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consumerinfo",
            name="contypeid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="index.consumertype"
            ),
        ),
        migrations.AddField(
            model_name="consumerinfo",
            name="installation_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="index.barangays"
            ),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name="consumerinfo",
            name="penaltycode",
            field=models.ForeignKey(
                default="POO1",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="index.penalty",
            ),
=======
            model_name='consumerinfo',
            name='penaltycode',
            field=models.ForeignKey(default='POO1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.penalty'),
>>>>>>> e468dea26d75b95be146daf09b9fb6e969dfb03a
        ),
        migrations.CreateModel(
            name="BarangayRecord",
            fields=[
                (
                    "barangayrec_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField()),
                ("total_due_jan", models.IntegerField(default=0)),
                ("total_paid_jan", models.IntegerField(default=0)),
                ("total_usage_jan", models.IntegerField(default=0)),
                ("total_due_feb", models.IntegerField(default=0)),
                ("total_paid_feb", models.IntegerField(default=0)),
                ("total_usage_feb", models.IntegerField(default=0)),
                ("total_due_mar", models.IntegerField(default=0)),
                ("total_paid_mar", models.IntegerField(default=0)),
                ("total_usage_mar", models.IntegerField(default=0)),
                ("total_due_apr", models.IntegerField(default=0)),
                ("total_paid_apr", models.IntegerField(default=0)),
                ("total_usage_apr", models.IntegerField(default=0)),
                ("total_due_may", models.IntegerField(default=0)),
                ("total_paid_may", models.IntegerField(default=0)),
                ("total_usage_may", models.IntegerField(default=0)),
                ("total_due_jun", models.IntegerField(default=0)),
                ("total_paid_jun", models.IntegerField(default=0)),
                ("total_usage_jun", models.IntegerField(default=0)),
                ("total_due_jul", models.IntegerField(default=0)),
                ("total_paid_jul", models.IntegerField(default=0)),
                ("total_usage_jul", models.IntegerField(default=0)),
                ("total_due_aug", models.IntegerField(default=0)),
                ("total_paid_aug", models.IntegerField(default=0)),
                ("total_usage_aug", models.IntegerField(default=0)),
                ("total_due_sept", models.IntegerField(default=0)),
                ("total_paid_sept", models.IntegerField(default=0)),
                ("total_usage_sept", models.IntegerField(default=0)),
                ("total_due_oct", models.IntegerField(default=0)),
                ("total_paid_oct", models.IntegerField(default=0)),
                ("total_usage_oct", models.IntegerField(default=0)),
                ("total_due_nov", models.IntegerField(default=0)),
                ("total_paid_nov", models.IntegerField(default=0)),
                ("total_usage_nov", models.IntegerField(default=0)),
                ("total_due_dec", models.IntegerField(default=0)),
                ("total_paid_dec", models.IntegerField(default=0)),
                ("total_usage_dec", models.IntegerField(default=0)),
                (
                    "barangaycode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="index.barangays",
                    ),
                ),
            ],
        ),
    ]
