# Generated by Django 4.0.6 on 2022-09-12 07:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('midname', models.CharField(blank=True, max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20)),
                ('mobilenum', models.CharField(blank=True, max_length=20)),
                ('usertype', models.CharField(choices=[('Admin', 'Admin'), ('Teller', 'Teller'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Meter Reader', 'Meter Reader')], max_length=20)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Barangays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meternumber', models.IntegerField()),
                ('firstname', models.CharField(blank=True, max_length=20)),
                ('middlename', models.CharField(blank=True, max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20)),
                ('initialmeterreading', models.IntegerField()),
                ('penaltyflag', models.BooleanField()),
                ('stopmeterflag', models.BooleanField()),
                ('deleteflag', models.BooleanField()),
                ('barangaycode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.barangays')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Penalties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minReading', models.IntegerField()),
                ('minReadingCharge', models.IntegerField()),
                ('rateAfterMin', models.IntegerField()),
                ('ratePenalty', models.IntegerField()),
                ('ratePenaltyFreq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transType', models.CharField(choices=[('j', 'j')], max_length=20)),
                ('meterReading', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('acctID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.consumerinfo')),
                ('discountcode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.discounts')),
                ('penaltyCode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.penalties')),
                ('processedBy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ratescode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.rates')),
            ],
        ),
        migrations.AddField(
            model_name='consumerinfo',
            name='statuscode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.status'),
        ),
        migrations.CreateModel(
            name='BarangayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_RecordID', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_due_jan', models.IntegerField()),
                ('total_paid_jan', models.IntegerField()),
                ('total_usage_jan', models.IntegerField()),
                ('total_due_feb', models.IntegerField()),
                ('total_paid_feb', models.IntegerField()),
                ('total_usage_feb', models.IntegerField()),
                ('total_due_mar', models.IntegerField()),
                ('total_paid_mar', models.IntegerField()),
                ('total_usage_mar', models.IntegerField()),
                ('total_due_apr', models.IntegerField()),
                ('total_paid_apr', models.IntegerField()),
                ('total_usage_apr', models.IntegerField()),
                ('total_due_may', models.IntegerField()),
                ('total_paid_may', models.IntegerField()),
                ('total_usage_may', models.IntegerField()),
                ('total_due_jun', models.IntegerField()),
                ('total_paid_jun', models.IntegerField()),
                ('total_usage_jun', models.IntegerField()),
                ('total_due_jul', models.IntegerField()),
                ('total_paid_jul', models.IntegerField()),
                ('total_usage_jul', models.IntegerField()),
                ('total_due_aug', models.IntegerField()),
                ('total_paid_aug', models.IntegerField()),
                ('total_usage_aug', models.IntegerField()),
                ('total_due_sept', models.IntegerField()),
                ('total_paid_sept', models.IntegerField()),
                ('total_usage_sept', models.IntegerField()),
                ('total_due_oct', models.IntegerField()),
                ('total_paid_oct', models.IntegerField()),
                ('total_usage_oct', models.IntegerField()),
                ('total_due_nov', models.IntegerField()),
                ('total_paid_nov', models.IntegerField()),
                ('total_usage_nov', models.IntegerField()),
                ('total_due_dec', models.IntegerField()),
                ('total_paid_dec', models.IntegerField()),
                ('total_usage_dec', models.IntegerField()),
                ('barangaycode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.barangays')),
            ],
        ),
    ]
