# Generated by Django 4.1.3 on 2023-01-04 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerinfo',
            name='discountcode',
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 10, 37, 35, 694644)),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='year',
            field=models.BigIntegerField(default=2023),
        ),
    ]
