# Generated by Django 4.1.3 on 2023-01-22 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 21, 9, 36, 824295)),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='profilepic',
            field=models.ImageField(blank=True, default='profile12.png', null=True, upload_to=''),
        ),
    ]
