# Generated by Django 4.0.6 on 2022-09-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='rateType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
