# Generated by Django 4.1.5 on 2023-04-17 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerinfo',
            name='first_tran',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 14, 43, 25, 843231)),
        ),
    ]
