# Generated by Django 4.1.5 on 2023-07-07 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfees',
            name='current_tran',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 14, 14, 42, 687186)),
        ),
    ]
