# Generated by Django 4.0.6 on 2022-10-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerinfo',
            name='current_bal',
            field=models.FloatField(default=0),
        ),
    ]
