# Generated by Django 4.0.6 on 2022-09-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='bill',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
