# Generated by Django 4.0.6 on 2022-09-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangayrecord',
            name='barangaycode',
        ),
    ]
