# Generated by Django 4.1.3 on 2022-11-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginRec",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("token", models.CharField(max_length=10)),
                ("last_access", models.DateTimeField()),
            ],
        ),
    ]
