# Generated by Django 4.1.3 on 2022-12-14 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginrec",
            name="expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 14, 10, 6, 13, 410791)
            ),
        ),
    ]
