# Generated by Django 4.0.6 on 2022-10-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerinfo',
            name='cummulative',
            field=models.FloatField(default=0),
        ),
    ]
