# Generated by Django 4.1.1 on 2022-09-12 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Penalties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='usertype',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teller', 'Teller'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Meter Reader', 'Meter Reader')], max_length=20),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transType', models.CharField(choices=[('j', 'j')], max_length=20)),
                ('meterReading', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('acctID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.consumerinfo')),
                ('discountcode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.discounts')),
                ('penaltyCode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.penalties')),
                ('processedBy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ratescode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.rates')),
            ],
        ),
    ]
