# Generated by Django 4.1.1 on 2022-10-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='daysappliedafter',
            field=models.IntegerField(default=0),
        ),
    ]
