# Generated by Django 4.1.5 on 2023-07-12 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 10, 42, 17, 344718)),
        ),
    ]
