# Generated by Django 4.1.5 on 2023-07-12 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfees',
            name='month_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 14, 53, 14, 843319)),
        ),
    ]
