# Generated by Django 4.1.1 on 2022-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
