# Generated by Django 4.0.6 on 2022-09-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usage_record',
            table=None,
        ),
    ]
