# Generated by Django 4.1.5 on 2023-07-11 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='issued_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 12, 26, 1, 59957)),
        ),
    ]
