# Generated by Django 4.1.1 on 2022-10-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transType',
            field=models.CharField(choices=[('Billing', 'Billing'), ('Payment', 'Payment'), ('Penalty', 'Penalty'), ('Discount', 'Discount')], max_length=20),
        ),
    ]
