# Generated by Django 4.0.6 on 2022-10-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerinfo',
            name='penaltyflag',
        ),
        migrations.AddField(
            model_name='consumerinfo',
            name='penaltycounter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
