# Generated by Django 4.1.5 on 2023-06-30 02:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerinfo',
            name='excep_accnt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 10, 5, 34, 440871)),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.issues')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFees',
            fields=[
                ('feeid', models.AutoField(primary_key=True, serialize=False)),
                ('fee_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('months', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('consumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.consumerinfo')),
            ],
        ),
    ]
