# Generated by Django 4.0.6 on 2022-09-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='bill',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='processedBy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
