# Generated by Django 4.0.5 on 2023-01-10 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 11, 49, 41, 116350)),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='profilepic',
            field=models.ImageField(blank=True, default='jazzy.jpg', null=True, upload_to=''),
        ),
    ]
