# Generated by Django 4.1.3 on 2022-11-08 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginrec",
            name="expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 8, 9, 57, 2, 635252)
            ),
        ),
    ]
