# Generated by Django 4.1.3 on 2022-12-14 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_alter_loginrec_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginrec",
            name="expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 14, 10, 31, 11, 223930)
            ),
        ),
        migrations.AlterField(
            model_name="systemusers",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
