# Generated by Django 4.1.3 on 2023-01-06 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_consumerinfo_discountcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 10, 11, 44, 612088)),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
