# Generated by Django 4.1.1 on 2023-01-26 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_loginrec_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 14, 23, 21, 7082)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='discountcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
