# Generated by Django 4.0.6 on 2022-09-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_transactions_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transactionid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
