# Generated by Django 4.1.3 on 2022-12-01 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_loginrec_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangayrecord',
            old_name='barangayrec_id',
            new_name='barangayrec',
        ),
        migrations.RenameField(
            model_name='consumerinfo',
            old_name='consumer_id',
            new_name='consumer',
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 12, 7, 44, 850777)),
        ),
    ]
