# Generated by Django 4.0.5 on 2023-01-10 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_loginrec_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 13, 51, 12, 942907)),
        ),
    ]
