# Generated by Django 4.1.5 on 2023-07-07 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_additionalfees_current_tran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfees',
            name='remainder',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 14, 44, 57, 472034)),
        ),
    ]
