# Generated by Django 4.1.1 on 2022-09-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_systemusers_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
