# Generated by Django 4.1.1 on 2022-11-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_penalty_daysappliedafter'),
        ('index', '0002_loginrec'),
    ]

    operations = [
    ]
