# Generated by Django 4.1.5 on 2023-06-30 02:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_consumerinfo_excep_accnt_alter_loginrec_expiration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='comments',
            new_name='last_comment',
        ),
        migrations.AddField(
            model_name='issues',
            name='issued_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 10, 41, 33, 290926)),
        ),
    ]
