# Generated by Django 4.0.6 on 2022-09-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_transactions_bill_alter_transactions_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='usage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
