# Generated by Django 4.1.1 on 2022-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_systemusers_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
