# Generated by Django 4.1.1 on 2022-09-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_consumerinfo_current_bal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Penalties',
            fields=[
                ('penaltycode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('penalty', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='consumerinfo',
            name='current_bal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='penalty_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rates',
            name='rate_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
