# Generated by Django 4.1.1 on 2022-09-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_discounts_penalties_alter_systemusers_usertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemusers',
            name='authorizedapprover',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='systemusers',
            name='firstname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
