# Generated by Django 4.1.3 on 2023-01-31 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_consumerinfo_date_added_alter_loginrec_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerinfo',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 23, 56, 39, 657807)),
        ),
    ]
