# Generated by Django 4.1.1 on 2022-11-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_loginrec_expiration'),
        ('index', '0003_merge_20221108_0937'),
    ]

    operations = [
    ]
