# Generated by Django 4.0.6 on 2022-09-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_systemusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='password',
            field=models.BinaryField(blank=True, editable=True, max_length=450),
        ),
    ]
