# Generated by Django 4.0.6 on 2022-09-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_transactions_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
