# Generated by Django 4.1.5 on 2023-06-30 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_comments_issues_last_comment_issues_issued_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerinfo',
            name='has_additionalfees',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 11, 24, 9, 322240)),
        ),
    ]
