# Generated by Django 4.1.1 on 2022-10-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_systemusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='password',
            field=models.BinaryField(blank=True, editable=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
