# Generated by Django 4.0.6 on 2022-09-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_transactions_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='is_reader',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='is_supervisor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='is_teller',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
