# Generated by Django 4.1.3 on 2022-12-01 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_barangayrec_id_barangayrecord_barangayrec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangayrecord',
            old_name='barangayrec',
            new_name='barangayrec_id',
        ),
        migrations.RenameField(
            model_name='consumerinfo',
            old_name='consumer',
            new_name='consumer_id',
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 14, 16, 29, 571293)),
        ),
    ]
