# Generated by Django 4.1.1 on 2022-10-04 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_consumerinfo_current_bal'),
        ('index', '0003_alter_systemusers_profilepic'),
    ]

    operations = [
    ]
