# Generated by Django 4.1.5 on 2024-03-26 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_loginrec_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='authors',
            field=models.CharField(default='Ryla, Charlie, Jazfer', max_length=100),
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 13, 38, 43, 622471)),
        ),
    ]
