# Generated by Django 4.2.1 on 2023-05-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_consumerinfo_first_tran_alter_loginrec_expiration'),
        ('index', '0003_alter_loginrec_expiration'),
    ]

    operations = [
    ]
