# Generated by Django 4.0.5 on 2023-01-27 02:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_loginrec_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerinfo',
            name='penaltycode',
            field=models.ForeignKey(default='POO1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.penalty'),
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 10, 44, 29, 998852)),
        ),
    ]
