# Generated by Django 4.0.6 on 2022-09-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_systemusers_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='authorizedapprover',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='is_reader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='is_teller',
            field=models.BooleanField(default=False),
        ),
    ]
