# Generated by Django 4.0.5 on 2023-01-10 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_loginrec_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 15, 59, 14, 504833)),
        ),
    ]
