# Generated by Django 4.1.5 on 2024-03-26 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_systeminfo_authors_alter_loginrec_expiration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemInfo',
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 13, 42, 12, 440878)),
        ),
    ]
