# Generated by Django 4.1.5 on 2023-02-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_consumerinfo_penaltycode_and_more'),
        ('index', '0005_alter_loginrec_expiration'),
    ]

    operations = [
    ]
