# Generated by Django 4.1.5 on 2024-03-26 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_delete_systeminfo_alter_loginrec_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.IntegerField(default=2024)),
                ('current_month', models.IntegerField(default=3)),
                ('authors', models.CharField(default='Ryla, Charlie, Jazfer', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 13, 42, 36, 256587)),
        ),
    ]
