# Generated by Django 4.0.6 on 2022-09-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_systemusers_authorizedapprover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='password',
            field=models.BinaryField(blank=True, max_length=450),
        ),
    ]
