# Generated by Django 4.1.1 on 2022-11-11 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_loginrec_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 13, 48, 41, 500594)),
        ),
    ]
