# Generated by Django 4.1.5 on 2023-02-03 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_merge_20230203_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerinfo',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 8, 26, 58, 565827)),
        ),
    ]
