# Generated by Django 4.1.5 on 2023-02-03 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_loginrec_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrec',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 9, 10, 6, 843787)),
        ),
    ]
