# Generated by Django 4.1.3 on 2023-01-11 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0008_alter_loginrec_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginrec",
            name="expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 11, 11, 59, 8, 494994)
            ),
        ),
    ]
